esphome:
  name: garage_door_sensor
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Pound Town"
  password: "carclockchair"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Door Sensor"
    password: "wsevDJtd8wxf"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "fjsoifnjsbfnvipf2342dwfv"

ota:
  password: "fjsoifnjsbfnvipf2342dwfv"

binary_sensor:

  - platform: status
    name: "Garage Door Sensor Status"

  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLDOWN
      inverted: True
    name: "door"
    device_class: garage_door

sensor:
  - platform: wifi_signal
    name: "Garage Door Sensor WiFi Status"
    update_interval: 60s
