esphome:
  name: garage-door-switch
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Pound Town"
  password: "carclockchair"

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 10.0.0.11
    # Set this to the IP address of the router. Often ends with .1
    gateway: 10.0.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Door Switch"
    password: "wsevDJtd8wxf"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "H9KmQf9fcrEvb65g"
  encryption:
    key: 2PDoDPOiREN/2Vk7BGsYSKTVLusZGPOr6gtLishXNy0=

ota:
  password: "H9KmQf9fcrEvb65g"

switch:
  - platform: gpio
    pin: 
      number: 14
      #mode: INPUT_PULLDOWN
      inverted: yes
    id: relay

  - platform: template
    name: "House Garage Door"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay


binary_sensor:

  - platform: status
    name: "Garage Door Switch Status"

sensor:
  - platform: wifi_signal
    name: "Garage Door Switch WiFi Status"
    update_interval: 60s

#esp32_ble_beacon:
  #type: iBeacon
  #uuid: '28321548-c938-748c-67a3-1155b4ca98aa'