[tool.poetry]
name = "esphome1"
version = "0.1.0"
description = ""
authors = ["Minura Ratnasekera <minura600@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
esphome = "^2023.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
