esphome:
  name: roller-door-sensor
  platform: ESP32
  board: nodemcu-32s

wifi:
  networks:
  - ssid: Pound Town
    password: carclockchair
    manual_ip:
      # Set this to the IP of the ESP
      static_ip: 10.0.0.22
      # Set this to the IP address of the router. Often ends with .1
      gateway: 10.0.0.1
      # The subnet of the network. 255.255.255.0 works for most home networks.
      subnet: 255.255.255.0

  - bssid: b0:95:75:f1:3e:aa
    password: carclockchair
    priority: 1
    manual_ip:
      # Set this to the IP of the ESP
      static_ip: 10.0.0.22
      # Set this to the IP address of the router. Often ends with .1
      gateway: 10.0.0.1
      # The subnet of the network. 255.255.255.0 works for most home networks.
      subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Roller Door Sensor"
    password: "wsevDJtd8wxf"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "fjsoifnjsbfnvipf2342dwfv"
  encryption:
    key: uwfADY+GXD6FD3o9D5Mk7zYDE7otq3uFkN4TWoxtNpw=

ota:
  password: "fjsoifnjsbfnvipf2342dwfv"

binary_sensor:

  - platform: status
    name: "Roller Door Sensor Status"

  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLDOWN
      inverted: True
    name: "Roller Door Binary Sensor"
    device_class: garage_door

sensor:
  - platform: wifi_signal
    name: "Roller Door Sensor WiFi Status"
    update_interval: 60s

#esp32_ble_beacon:
  #type: iBeacon
  #uuid: '89522fcf-f295-736f-facf-2a3eba7973e8'